data/django/magimaps/config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/main/index.html/index.html"), name="home"),
    path("about/",TemplateView.as_view(template_name="pages/about.html"),name="about",),
    path("map/", views.AccountSettingsView.as_view(template_name="pages/app/map.html/map.html"), name='map'),
    #path("map/", views.map, name='map'),
    path(settings.ADMIN_URL, admin.site.urls),
    path("users/", include("magimaps.users.urls", namespace="users"),),
    path("accounts/login/", views.JointLoginSignupView.as_view(template_name="pages/main/signup.html/signup.html"), name='login'),
    path("accounts/", include("allauth.urls")),

    
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

data/django/magimaps/magimaps/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>/",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

data/django/magimaps/magimaps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

data/django/magimaps/magimaps/users/forms.py
from django import forms

class SignupForm(forms.Form):
    email = forms.CharField(max_length=254)
    password1 = forms.CharField(widget=forms.PasswordInput)
    
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__( *args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.field_class = ''
        self.helper.layout = Layout(
            Field('email', placeholder='Email', autocomplete='off'),
            Field('password1', placeholder='Password', autocomplete='off'),
            
            Div(Submit('Register', 'Register', css_class='btn btn-primary block full-width m-b'), css_class='form-group'),
            HTML('<p class="text-muted text-center"><small>Already have an account?</small></p>'),
            Div(HTML('<a class ="btn btn-sm btn-white btn-block" href="' + reverse('account_login') + ' " > Login </a>'),css_class='form-group' )
        )

    def signup(self, request, user):
        user.email = self.cleaned_data['email']
        user.save()

data/django/magimaps/config/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from allauth.account.views import *
from django.contrib.auth.mixins import LoginRequiredMixin

##def map(request):
#    if request.user.is_authenticated:
#        template_name = 'pages/map.html'
#        accounts = AccountSettingsView
#        return render(request, template_name, accounts)
#        #return render(request, 'pages/map.html')
#    else:
#        return redirect('/')

    
class JointLoginSignupView(LoginView):
    form_class = LoginForm
    signup_form = SignupForm
    change_password = ChangePasswordForm
    def get_context_data(self, **kwargs):
        ret = super(JointLoginSignupView, self).get_context_data(**kwargs)
        ret['signupform'] = get_form_class(app_settings.FORMS, 'signup', self.signup_form)
        ret['changepasswordform'] = get_form_class(app_settings.FORMS, 'changepassword', self.change_password)
        return ret
 
login = JointLoginSignupView.as_view()

class AccountSettingsView(LoginRequiredMixin, PasswordChangeView):
    form_class = ChangePasswordForm
    email_form = AddEmailForm

    def get_context_data(self, **kwargs):
        ret = super(AccountSettingsView, self).get_context_data(**kwargs)
        ret['addemailform'] = get_form_class(app_settings.FORMS, 'add_email', self.email_form)
        return ret
    

data/django/magimaps/magimaps/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

data/django/magimaps/magimaps/templates/pages/app/map.html/help/help.html
<div id="help" class="hidden">
  <div id="help-content">
    <div id="help-nav">
      <span id="help-getting-started" class="help-nav-button active">Getting Started</span>
      <span id="help-contact" class="help-nav-button">Contact</span>
      <span id="help-examples" class="help-nav-button">Examples</span>
      <span id="help-documentation" class="help-nav-button">Documentation</span>
    </div>
    <div id="help-active">
      <fieldset id="help-getting-started-content">
	<p class="first-step"><b>1.</b> Click the <b>Options</b> tab in the navigation bar, at the top of this page</p>
	<p class="first-step"><b>2.</b> In the top left-hand corner of the <b>Options</b> page is the <b>Specificty</b> box. Choose
	  what type of place you want to search for, from the dropdown in this box
	<span><i>Ex.</i> If you would like to find out how many fire stations are in each state, you would
	  pick "States"</span></p>
	<p class="first-step"><b>3.</b> Below the <b>Specificty</b> box is the <b>Areas</b> box. Click each check-box next to the states you would like to include in your search
	<span><i>Ex.</i> If you woud like to search for how many fire stations are in "Alaska," "Florida," and "Hawaii," you would click the checkboxes next to those states</span></p>
	<p class="first-step"><b>4.0</b> To the right of the <b>Areas</b> box is the <b>Info</b> box. If you chose "States" under the "Specificty" box, it should say <b>State Info</b>. In this box, there are different categories of information
	<span><i>Ex.</i> Government-related information, like number of "Fire Stations," is under the "Government" category</span></p>
	<p class="first-step"><b>4.1</b> In each category are individual options for information. Each option has a dropdown menu to the right of it where you can decide what characteristics to include
	  <span><i>Ex.</i> If you would like to find how out many fire stations are in your specific states, you would go under the "Government" category. Then, you would find "Fire Stations" and select "Greater Than" in its dropdown box</span></p>
	<p class="first-step"><b>4.2</b> After you choose a specific characteristic, another box will appear to the right of the option. In this box, you can narrow down your chosen characteristic to within your chosen number range
	  <span><i>Ex.</i> If you would like to find only places with 100 or more fire stations, you would go to the "Fire Stations" characteristic, choose "Greater Than" from the dropdown to the right of it, and then type "100" in the new box that appears</span></p>
	<p class="first-step"><b>5.</b> Once you've chosen all of your options, you can hit submit in the top right-hand corner of the <b>Options</b> page, to be taken to the <b>Results</b> page to view your results</p>
      </fieldset>
    </div>
  </div>
</div>

data/django/magimaps/magimaps/templates/pages/app/map.html/map.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
{{ block.super }} | Main App
{% endblock title %}
{% block css %}
{% include './nav/nav.css' %}
{% include './options/options.css' %}
{% include './map.html.css' %}
{% include './map/map.css' %}
{% include './results/results.css' %}
{% include './help/help.css' %}
{% include './account/account.css' %}
{% include './viewports.css' %}
{% endblock css %}
{% block head %}
<meta name="description" content="Magi Maps main webapp page. Here lives the beating heart of the whole operation.">
{% include 'pages/app/resources/openlayers/ol.html' %}
{% endblock head %}
{% block content %}
<div id="body-container">
  {% include './nav/nav.html' %}
  <div id="map" class="map">
    {% include './options/options.html' %}
    {% include './results/results.html' %}
    {% include './help/help.html' %}
    {% include './account/account.html' %}
  </div>
</div>
<div id="info">
<script src="{% static 'templates/pages/app/resources/openlayers/ol.js' %}"></script>
<script src="{% static 'templates/pages/app/map.html/map.html.js' %}"></script>
{% endblock content %}

data/django/magimaps/magimaps/templates/pages/app/map.html/options/extra-options-counties.html
<fieldset id="extra-options-county" class="extra-options option-fieldset hidden" style="display: inline-block;">
  <legend>County Info</legend>
  <span class="extra-options-header">Government </span>
  <label>Police Stations: <select data-sql="police_stations" name="area-select" placeholder="" selected="null" value="" onchange="resizeOptionDropdown(this)";>
      <option value="null" selected=""></option>
      <option value="PropertyIsGreaterThan">Greater than (#)</option>
      <option value="PropertyIsLessThan">Less than (#)</option>
    </select>
    <input type="number" data-sql="police_stations" onchange="" data-type="number">
  </label>
  <label>Fire Stations: <select data-sql="fire_stations" name="area-select" placeholder="" selected="null" value="" onchange="resizeOptionDropdown(this)">
      <option value="null" selected=""></option>
      <option value="PropertyIsGreaterThan">Greater than (#)</option>
      <option value="PropertyIsLessThan">Less than (#)</option>
    </select>
    <input type="number" data-sql="fire_stations" value="" onchange="" data-type="number">
  </label>
</fieldset>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/extra-options-nation.html
<fieldset id="extra-options-nation" class="extra-options option-fieldset hidden" style="display: inline-block;">
  <legend>Nation Info</legend>
  <span class="extra-options-header">Government </span>
  <label>Police Stations: <select data-sql="police_stations" name="area-select" placeholder="" value="" selected="null" onchange="resizeOptionDropdown(this)";>
      <option value="null" selected=""></option>
      <option value="nation">Total</option>
    </select>
    <input data-type="nation">
  </label>
  <label>Fire Stations: <select data-sql="fire_stations" name="area-select" placeholder="" value="" selected="null" onchange="resizeOptionDropdown(this)">
      <option value="null" selected=""></option>
      <option value="nation">Total</option>
    </select>
    <input data-type="nation">
  </label>
</fieldset>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/extra-options-states.html
<fieldset id="extra-options-state" class="extra-options option-fieldset" style="display: inline-block;">
  <legend>State Info</legend>
  <span class="extra-options-header">Government </span>
  <label>Police Stations: <select data-sql="police_stations" name="area-select" selected="null" placeholder="" value="" onchange="resizeOptionDropdown(this)";>
      <option value="null" selected=""></option>
      <option value="PropertyIsGreaterThan">Greater than (#)</option>
      <option value="PropertyIsLessThan">Less than (#)</option>
    </select>
    <input type="number" data-sql="police_stations" onchange="" data-type="number">
  </label>
  <label>Fire Stations: <select data-sql="fire_stations" selected="null" name="area-select" placeholder="" value="" onchange="resizeOptionDropdown(this)">
      <option value="null" selected=""></option>
      <option value="PropertyIsGreaterThan">Greater than (#)</option>
      <option value="PropertyIsLessThan">Less than (#)</option>
    </select>
    <input type="number" data-sql="fire_stations" value="" onchange="" data-type="number">
  </label>
</fieldset>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/extra-options.html
{% include './extra-options-nation.html' %}
{% include './extra-options-states.html' %}
{% include './extra-options-counties.html' %}

data/django/magimaps/magimaps/templates/pages/app/map.html/options/main-options.html
<fieldset id="main-options" class="option-fieldset" style="display: inline-block;">
  <legend>Specificity</legend>
  <select id="main-level-select" name="area-select">
    <option value="nation">Nation</option> 
    <option value="state" selected="">States</option>
    <option value="county">Counties</option>
    </select>
</fieldset>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/options.html
<div id="options">
  {% include './main-options.html' %} 
  <br>
  {% include './supp-options.html' %}  
  {% include './extra-options.html' %}
  {% include './submit-options.html' %}
</div>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/submit-options.html
<fieldset id="submit-options">
  <div id="submit-options-container">
    <label id="goto-select">Go To: <select class="submit-select" name="submit-select" selected="results" placeholder="" value="results">
	<option value="null"></option>
	<option value="results" selected>Results</option>
	<option value="ol-viewport">Map</option>
      </select>
    </label>
    <a class="regular-button important-button" onclick="submitOptions(this);">Submit</a>
  </div>
</fiedlset>

data/django/magimaps/magimaps/templates/pages/app/map.html/options/supp-options.html
<fieldset id="supp-options" class="option-fieldset" style="display: inline-block;">
  <legend>Areas (<span id="areas-all"><span id="areas-selected">0</span>/52</span>)</legend>
  <form name="theForm">
    <label><input type="checkbox" name="answers[]" value="javascript">All</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Alabama</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Alaska</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Arizona</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Arkansas</label>
    <label><input type="checkbox" name="answers[]" value="javascript">California</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Colorado</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Connecticut</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Delaware</label>
    <label><input type="checkbox" name="answers[]" value="javascript">D.C</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Florida</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Georgia</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Hawaii</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Idaho</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Illinois</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Indiana</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Iowa</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Kansas</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Kentucky</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Louisiana</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Maine</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Maryland</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Massachusetts</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Michigan</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Minnesota</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Mississippi</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Missouri</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Montana</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Nebraska</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Nevada</label>
    <label><input type="checkbox" name="answers[]" value="javascript">New Hampshire</label>
    <label><input type="checkbox" name="answers[]" value="javascript">New Jersey</label>
    <label><input type="checkbox" name="answers[]" value="javascript">New Mexico</label>
    <label><input type="checkbox" name="answers[]" value="javascript">New York</label>
    <label><input type="checkbox" name="answers[]" value="javascript">North Carolina</label>
    <label><input type="checkbox" name="answers[]" value="javascript">North Dakota</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Ohio</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Oklahoma</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Oregon</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Pennsylvania</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Puerto Rico</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Rhode Island</label>
    <label><input type="checkbox" name="answers[]" value="javascript">South Carolina</label>
    <label><input type="checkbox" name="answers[]" value="javascript">South Dakota</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Tennessee</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Texas</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Utah</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Vermont</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Virginia</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Washington</label>
    <label><input type="checkbox" name="answers[]" value="javascript">West Virginia</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Wisconsin</label>
    <label><input type="checkbox" name="answers[]" value="javascript">Wyoming</label>
    <br>
  </form>
</fieldset>

data/django/magimaps/magimaps/templates/pages/app/map.html/results/results.html
<div id="results" class="hidden results-before">
  <span>No results requested.</span>
</div>

data/django/magimaps/magimaps/templates/pages/app/resources/openlayers/ol.html
<!-- openlayers header -->
<!--<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL"></script>-->
<script>(function(undefined) {}).call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});</script>
<style>{% include './ol.css' %}</style>

data/django/magimaps/magimaps/templates/pages/main/base_main.html
{% extends 'base.html' %}
{% block css %}
{% include 'pages/main/resources/nav/nav.css' %}
{% include 'pages/main/resources/footer/footer.css' %}
{% include 'pages/main/resources/css/viewports.css' %}
{% endblock css %}
{% block content %}
{% include 'pages/main/resources/nav/nav.html' %}
{% block extended_content %}
{% endblock extended_content %}
{% include 'pages/main/resources/footer/footer.html' %}
<script>{% include './resources/nav/burger_functionality.js' %}</script>
{% endblock content %}

data/django/magimaps/magimaps/templates/pages/main/password_reset.html/password_reset.html
{% extends 'pages/main/base_main.html' %}
{% block title %}
{{ block.super }} | Reset Password
{% endblock title %}
{% block css %}
{{ block.super %}}
{% include 'pages/resources/signup.html/signup.html.css' %}
{% endblock css %}
{% block head %}
<meta name="description" content="Magi Maps, the real estate visualizer that's quick and easy to use. Gain valuable insights on any location in the U.S without wasting time.">
{% endblock head %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block extended_content %}

<div id="main">

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>

{% endblock extended_content %}

data/django/magimaps/magimaps/templates/pages/main/resources/footer/footer.html
<!-- global footer -->
<footer>
  <span class="copyright"><a href="https://www.magimaps.com">&copy; {% now "Y" %} Magi Maps</a></span>
</footer>

data/django/magimaps/magimaps/templates/pages/main/resources/nav/nav.html
{% load staticfiles %}
<!-- global navbar -->
<nav class="nav" id="nav">
  <div class="nav-button-container">
    <a class="nav-button logo" href="{% url 'home' %}" accesskey="a"><img id="logo" src="{% static 'images/logo.svg' %}" width="76" height="77" alt="Magi Maps">Magi Maps</a>
    <a class="developers-nav nav-button not-mobile" href="demo" accesskey="c">Contact</a>
    <a class="company-nav nav-button not-mobile" href="{% url 'about' %}" accesskey="d">About</a>
    <a class="nav-button signin-nav not-mobile" href="{% url 'map' %}" accesskey="g">Account  &raquo;</a>
    <a class="nav-button burger" id="burger-button" accesskey="5"><img id="burger-button-img" src="{% static 'images/burger.svg' %}" width="76" height="77" alt="Burger Bar"></a>
    <div id="burger-menu">
      <p class="medium"><a href="{% url 'map' %}">Account  &raquo;</a></p>
      <p class="medium"><a href="{% url 'about' %}">About</a></p>
      <p class="medium"><a href="demo">Contact</a></p>
    </div>
  </div>
</nav>

data/django/magimaps/magimaps/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

data/django/magimaps/magimaps/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

data/django/magimaps/magimaps/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}